### ISSUE TITLE
Write variable attributes to raster format

### ISSUE THREAD

**Issue by kylemann16** [hobuinc/silvimetric#4]
TreeTally should be able to accept a list of attributes to transform from TileDB to raster format.

**Comment by hobu** [comment]
IMO it should write the default set and users must opt-out of things they don't want. We should match FUSION's behavior.

**Comment by kylemann16** [comment]
I was thinking every attribute in the pointcloud would be written to TileDB, but I was thinking it might be too much to write every attribute with every metric out to rasters.

**Comment by hobu** [comment]
> I was thinking every attribute in the pointcloud would be written to TileDB

ah, I was thinking of only writing

* `Z`
* `HeightAboveGround`
* `Intensity`
* `ReturnNumber`
* `NumberOfReturns`
* `Classification`

Also, the ingest side needs to strip withheld and overlaps: `"where":"Withheld!=1 or Overlap != 1"`

**Comment by kylemann16** [comment]
Addressed in #21
