### ISSUE TITLE
Add 'estimate_tilesize' kernel

### ISSUE THREAD

**Issue by hobu** [hobuinc/silvimetric#50]
The current implementation of `shatter` attempts to adaptively figure out the tilesize to keep the number of points being sent off to each task to be under a threshold (currently 600k). This is useful for figuring out the tile size, but it it is extra compute cost that we don't need to spend for *every* shatter operation, especially if each one is a different chunk of a larger set – presumably with similar density characteristics.

The spool up in this image is the splitting and density estimation. We don't need to pay this for every shatter, and we currently provide a `tilesize` option to short circuit doing it. 
![image](https://github.com/hobuinc/silvimetric/assets/87751/669f7405-15b6-4647-995d-bf0a1d0bbfee)

We need something like 

```
silvimetric database.smdb estimate_tilesize --threshold 600000 mypipeline.json
```

The result of this run would be

```
mean:
median:
stddev:

suggested: median + 2*stddev
```

For the suggested, we are assuming that it is better to over select data than it is to over task Dask. Depending on people's computing configuration, that might not be a true assumption. We will print enough stats to let them 🦶 🔫 themselves.

**Comment by kylemann16** [comment]
Added in #53

**Comment by kylemann16** [comment]
Added in #53
