### ISSUE TITLE
Create init command

### ISSUE THREAD

**Issue by kylemann16** [hobuinc/silvimetric#7]
Create `init` command that handles the creation of the tiledb database. 

- `init` command should have a default config that can overridden by a yaml/json file from user input.
- Command should have a test associated with it that tests"
  - That the command/class accepts the correct parameters and handles them correctly
  - That users can input a file and have that handled correctly
  - That the tiledb created from this class/command is generated correctly

**Comment by hobu** [comment]
Init must write the following
* `resolution` 
* `bounds`
* `crs`
* `attributes` (using PDAL Dimension names)

**Comment by hobu** [comment]
Complete in #24
