### ISSUE TITLE
Create shatter command/class

### ISSUE THREAD

**Issue by kylemann16** [hobuinc/silvimetric#8]
Create `shatter` command/class entrypoint into TreeTally. 

- Should accept and handle a set of arguments that allows user to define how TreeTally will break up and analyze pointcloud datasets
- There should be a test associated with this class/command says:
  - that arguments are accepted and handled correctly
  - That data is correctly chunked according to the chunk size and resolution
  - That points are being assigned to the correct cells
  - That the indices derived with a `Bounds` class is correct and covers the entire span of the dataset defined
  - That the data is correctly using the quad tree filter to pre-filter sections of the bounds that hold no data
  - That the data written out to the tiledb database is correct

**Comment by hobu** [comment]
Every file insertion must be logged in the tdb metadata. This could just be `pdal info` output dumped into tdb's metadata.

**Comment by kylemann16** [comment]
Solidified Shatter command in #27
