### ISSUE TITLE
Create info command/class

### ISSUE THREAD

**Issue by kylemann16** [hobuinc/silvimetric#9]
Create `info` command/class, which analyzes a filled tiledb database and tells the user information about it.

Create test for `info` command that says:
 - That the information is being read correctly
 - That metadata stored in the tiledb database is correctly stored as read-only
 - That arguments passed to this command are correctly handled

**Comment by hobu** [comment]
`info` should have the following features

* `--json` mode emits the content in JSON format
* Normal stdout printing emits Markdown format to print to terminal
* The `resolution` of the tdb
* The `bounds` of the tdb in GeoJSON format
* The `extent` of the tdb
* A list of the files that have been inserted into the database, when they were inserted, how many points each file had, and what the geography of the file was that was
* The `srs` of the tdb in PROJJSON and WKT2 formats
* A list of the attribute slots available

**Comment by kylemann16** [comment]
Addressed in #27
