### ISSUE TITLE
Python TypeError when executing script to transform the bounding box and create an interactive map

### ISSUE THREAD

**Issue by Oresso1** [hobuinc/silvimetric#92]
I'm currently utilizing the SilviMetric Demo in a Colab environment. I have installed CondaColab successfully as well as all of SilviMetric dependencies. I was also able to successfully import all necessary packages during the "Setup" stage. But once I import the packages and run the next script to transform the bounding box and create an interactive map, I received an error "TypeError: Argument 'bbox' has incorrect type (expected tuple, got list)" 
![Error240903](https://github.com/user-attachments/assets/22678efc-57ec-46fc-8713-9f765261004b)
![TypeError2](https://github.com/user-attachments/assets/0235f413-5e98-4614-af7e-fe36d6be16f1)

**Comment by kylemann16** [comment]
Thanks for the issue, will look into this

**Comment by kylemann16** [comment]
Should be fixed now with pushes of #93 and #94, had a couple of things to implement to catch up to dependency updates. Let me know if you're able to run it now.

Thank you for bringing this to our attention!

**Comment by kylemann16** [comment]
Closing this for now. If you still have problems feel free to re-open.
