### ISSUE TITLE
State supported pointcloud formats in documentation

### ISSUE THREAD

**Issue by rrowlands** [hobuinc/silvimetric#98]
The official Silvimetric documentation does not state which pointcloud formats are supported.

**Comment by rrowlands** [comment]
Ah interesting. I thought PDAL supported las / laz ?

**Comment by hobu** [comment]
> Maybe las / laz isn't a "spatially organized point cloud format"?

Not by themselves, no. COPC makes LAZ a spatially organized format. Watch me talk about the distinction at https://www.youtube.com/watch?v=xJabqDBMm-A
